import 'dotenv/config';import { PrismaPg } from '@prisma/adapter-pg';import { PrismaClient } from '../src/generated/prisma/client';import bcrypt from 'bcryptjs';
const cs=process.env.DATABASE_URL;if(!cs)throw new Error('DATABASE_URL required');const db=new PrismaClient({adapter:new PrismaPg({connectionString:cs})});
async function main(){
 const plans=[['free','Free',0,30],['pro','Pro',1900,300],['business','Business',5900,1500],['enterprise','Enterprise',0,10000]] as const;for(const [slug,name,price,daily] of plans)await db.plan.upsert({where:{slug},create:{slug,name,priceMonthly:price,dailyRequests:daily,description:`${name} plan for growing AI workflows`},update:{name,priceMonthly:price,dailyRequests:daily}});
 const pw=await bcrypt.hash('DemoPassword123',12);const superAdmin=await db.user.upsert({where:{email:'superadmin@nexa.demo'},create:{name:'Nexa Super Admin',email:'superadmin@nexa.demo',passwordHash:pw,role:'SUPER_ADMIN',emailVerifiedAt:new Date(),onboardingCompletedAt:new Date()},update:{role:'SUPER_ADMIN'}});const admin=await db.user.upsert({where:{email:'admin@nexa.demo'},create:{name:'Nexa Admin',email:'admin@nexa.demo',passwordHash:pw,role:'ADMIN',emailVerifiedAt:new Date(),onboardingCompletedAt:new Date()},update:{role:'ADMIN'}});const user=await db.user.upsert({where:{email:'demo@nexa.demo'},create:{name:'Demo User',email:'demo@nexa.demo',passwordHash:pw,emailVerifiedAt:new Date(),onboardingCompletedAt:new Date()},update:{}});
 const free=await db.plan.findUniqueOrThrow({where:{slug:'free'}});for(const u of [superAdmin,admin,user]){if(!await db.subscription.findFirst({where:{userId:u.id,status:'ACTIVE'}}))await db.subscription.create({data:{userId:u.id,planId:free.id,status:'ACTIVE'}});await db.userSettings.upsert({where:{userId:u.id},create:{userId:u.id},update:{}});}
 const providers=[['GEMINI',1,process.env.GEMINI_MODEL??'gemini-3.5-flash-lite'],['OPENROUTER',2,process.env.OPENROUTER_MODEL??'openrouter/free'],['CLOUDFLARE',3,process.env.CLOUDFLARE_MODEL??'@cf/zai-org/glm-4.7-flash']] as const;for(const [provider,priority,defaultModel] of providers){await db.aIProviderConfig.upsert({where:{provider},create:{provider,priority,defaultModel},update:{priority,defaultModel}});const existing=await db.aIModel.findFirst({where:{provider,modelId:defaultModel,feature:null}});if(!existing)await db.aIModel.create({data:{provider,modelId:defaultModel,displayName:defaultModel,enabled:true,isDefault:true,priority}});}
 const cat=await db.category.upsert({where:{slug:'ai-productivity'},create:{name:'AI & Productivity',slug:'ai-productivity'},update:{}});const posts=[['build-reliable-ai-workflows','How to Build Reliable AI Workflows','Design AI features that survive provider outages, quotas, and latency spikes.'],['prompt-systems-at-scale','Prompt Systems at Scale','Move prompts out of UI components and into a versionable, testable layer.'],['saas-security-basics','Security Basics for Modern SaaS','Practical controls for sessions, authorization, rate limits, and secrets.']];for(const [slug,title,excerpt] of posts)await db.blogPost.upsert({where:{slug},create:{slug,title,excerpt,content:`# ${title}

${excerpt}

This demo article is seeded with realistic product guidance so the blog is usable immediately. Replace or expand it from the admin content workflow.`,published:true,featured:slug===posts[0][0],publishedAt:new Date(),authorId:admin.id,categoryId:cat.id,seoTitle:title,seoDescription:excerpt},update:{}});
 const tags=[];for(const [name,slug] of [['AI Architecture','ai-architecture'],['SaaS','saas'],['Security','security']])tags.push(await db.tag.upsert({where:{slug},create:{name,slug},update:{name}}));const firstPost=await db.blogPost.findUnique({where:{slug:'build-reliable-ai-workflows'}});if(firstPost)await db.blogPost.update({where:{id:firstPost.id},data:{tags:{set:tags.map(t=>({id:t.id}))}}});
 const conv=await db.conversation.findFirst({where:{userId:user.id}})??await db.conversation.create({data:{userId:user.id,title:'Launch plan brainstorm'}});if(await db.message.count({where:{conversationId:conv.id}})===0)await db.message.createMany({data:[{conversationId:conv.id,role:'USER',content:'Help me turn a product idea into a launch checklist.'},{conversationId:conv.id,role:'ASSISTANT',content:'Start with audience, promise, activation path, measurement, and a narrow launch channel.',provider:'GEMINI',model:'demo'}]});
 if(await db.notification.count({where:{userId:user.id}})===0)await db.notification.createMany({data:[{userId:user.id,title:'Welcome to Nexa AI',body:'Your AI workspace is ready.',type:'ACCOUNT',href:'/dashboard/ai'},{userId:user.id,title:'Free plan active',body:'Your usage limits reset daily.',type:'BILLING',href:'/dashboard/billing'}]});
 if(await db.supportTicket.count({where:{userId:user.id}})===0)await db.supportTicket.create({data:{userId:user.id,subject:'Getting started with AI tools',description:'Where can I find my recent generations?',status:'RESOLVED',priority:'LOW'}});
 console.log('Seed complete. Demo password: DemoPassword123');
}
main().finally(()=>db.$disconnect());
